version: "3"

services:
    app:
        image: python:3.11-buster
        container_name: app
        hostname: web
        working_dir: "/application/"
        entrypoint: "bash entrypoint.sh"
        environment:
          - PYTHONUNBUFFERED=1
        volumes:
          - app-python3.11-site-packages:/usr/local/lib/python3.11/site-packages
          - app-python3.11-usr-local-bin:/usr/local/bin
          - .:/application
        depends_on:
          - redis
        ports:
          - "5000:5000"
        stdin_open: true
        tty: true

    redis:
        image: redis:7.2.0
        container_name: redis
        ports:
          - "6379:6379"


volumes:
    app-python3.11-site-packages:
    app-python3.11-usr-local-bin: